name: Run Tests (manual)

on:
  workflow_dispatch:

jobs:
  call-tests:
    uses: ./.github/workflows/test.yml
    secrets:
        DATASCRIBE_API_TOKEN: ${{ secrets.DATASCRIBE_API_TOKEN }}
        DATASCRIBE_ADMIN_API_TOKEN: ${{ secrets.DATASCRIBE_ADMIN_API_TOKEN }}
